/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Rocks(props: any) {
  const { nodes, materials } = useGLTF(
    "/demo-2024-a-storm-at-midnight/props.glb"
  ) as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.smallrock2_smallrocks_0.geometry}
        material={materials.smallrocks}
        material-roughness={0.2}
      />
    </group>
  );
}
