/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Sign(props: any) {
  const { nodes, materials } = useGLTF(
    "/demo-2024-a-storm-at-midnight/props.glb"
  ) as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface7_Traffic_Signs_0001.geometry}
        material={materials.Traffic_Signs}
        position={[0, 0, 0.263]}
        scale={0.01}
        material-roughness={0.2}
      />
    </group>
  );
}
